### ISSUE TITLE
EOL flag on branches?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/updater_server#108]
It would be nice if we could view the notifications and the update check differently when the version running is EOL.
So I would propose to add a `'eol' => '1',` to the arrays of https://github.com/nextcloud/updater_server/blob/master/config/config.php#L154
Would be nice if we can agree on something here quickly, so we can put code for that in the last 11 release.

**Comment by nickvergessen** [comment]
cc @rullzer @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
:+1: 
Then this would show some kind of real hard warning for 11.x once NC14 is out?

**Comment by nickvergessen** [comment]
actually 11 goes EOL with the next release, since it ends just after 13

**Comment by nickvergessen** [comment]
I would:
1. Change the admin sections and add some red to it
2. Change the wording on the notification to reflect EOL
3. Make the update notification re-appear monthly/4-weekly

Customers running a EOL version should get a different updater server

**Comment by MorrisJobke** [comment]
Sounds good and also please make this a native notification for admin users and not the weird banner there at the top.

**Comment by nickvergessen** [comment]
The banner is only shown until Nextcloud 9 or when the notification app is not enabled.
I think that's acceptable…

**Comment by MorrisJobke** [comment]
@nickvergessen Is this already in any code available?

**Comment by nickvergessen** [comment]
no, on my todo for this week
