### ISSUE TITLE
stable14 daily builds are missing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/updater_server#147]
there is only master right now.

**Comment by MorrisJobke** [comment]
Big question: does it make sense to provide dailies? As you can't upgrade between them anyways 🙈

**Comment by nickvergessen** [comment]
well we have dailies for all other stable branches and master. So I guess stable14 should also be there.

**Comment by MorrisJobke** [comment]
Okay - I will add it once the release script is updated. https://github.com/nextcloud-gmbh/release-script/pull/2

**Comment by MorrisJobke** [comment]
There are now stable14 and stable15 dailies.

**Comment by MorrisJobke** [comment]
> There are now stable14 and stable15 dailies.

And master ones as well.
