### ISSUE TITLE
ipv6-only hosts cannot use the updater

### ISSUE THREAD

**Issue by MEschenbacher** [nextcloud/updater_server#154]
I'm not sure if this is the right place for reporting this issue:

I'm using official nextcloud 14.0.1 and trying to upgrade to 14.0.3.
The auto updater app does not load when trying to update by clicking 'open updater' using an ipv6-only host. This might be because updates.nextcloud.org only resolves to a single legacy-ip.
I've confirmed that using a dualstack host correctly loads the updater and lets me go through with the update.

**Comment by rullzer** [comment]
Our updater server is ipv6 now as well. So this is fixed as far as I can tell :)

**Comment by MEschenbacher** [comment]
Great news! Thank you for fixing the issue.
