### ISSUE TITLE
Move 15.0.2 to 100%

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/updater_server#185]
Could we move the 14.0.x users 100% to 15.0.2? Or are there issues we wait for that will be fixed in 15.0.3? Us being super conservative with this results in super regular questions and comments like
https://twitter.com/stefan2sander/status/1090925131763986432

And they have a point... We should be more consistent - go to 100% after the 1nd minor release unless there's a real good reason not to.

**Comment by MorrisJobke** [comment]
There are good reasons and they are fixed in .3. ;) we will do it in 2 weeks from now because then the stable is out for one week

**Comment by MorrisJobke** [comment]
stable14 ships 100% 15.0.x.

And #188 will ship 15.0.x on production channel 14 instances.
