### ISSUE TITLE
Response should contain that a new version is blocked due to php version

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/updater_server#239]
I hope this is the right place, sorry if I'm missing something obvious here.

I was wondering why my nextcloud 15.0.9 instance did not offer a upgrade to 16.0.2, although being released for a while now. First I thought this was due to a iterative rollout of the release to the user, but digging deeper I found that my php verison 7.0 was the problem here. The updater just skips releases which require a newer php version: https://github.com/nextcloud/updater_server/blob/14521d675c9323f1b9aa410eb0b36036ddbd090d/src/Response.php#L91-L93
While I agree that a upgrade to an incompatible version should be prevented, I was wondering if there should be a notification to the user?! I think it should not fail silently. Instead of "You're up to date" something like "There's a new major version available which is incompatible with your server configuration / PHP version. Please check the requirements for Nextcloud [NEW_MAJOR_VERSION] at [URL]".

**Comment by MorrisJobke** [comment]
We deployed exactly this yesterday: #229 but it seem to have some visual issues on the server side: https://github.com/nextcloud/server/issues/16316

Thus I will close this here and we continue in the server.

**Comment by SystemKeeper** [comment]
Ah, thanks @MorrisJobke !
