### ISSUE TITLE
Updater doesn't suggest Nextcloud 17

### ISSUE THREAD

**Issue by Zelphy** [nextcloud/updater_server#268]
Hi,

Nextcloud does not propose the update from 16 to 17 on the **stable** channel via the web interface. It tells me I'm up-to-date:

![nextcloud_update](https://user-images.githubusercontent.com/4152786/66193950-dcc52780-e693-11e9-8107-a3f08ee45e09.png)

On the **beta** channel, it seems to work:

![Screenshot from 2019-10-04 10-32-15](https://user-images.githubusercontent.com/4152786/66194191-46453600-e694-11e9-994d-3342a097b7b4.png)

The last stable should be 17.0.0 according to the website:

![Screenshot from 2019-10-04 10-32-37](https://user-images.githubusercontent.com/4152786/66194266-61b04100-e694-11e9-86db-5b762288b840.png)
 
In config.php:

latest **production** is 16: https://github.com/nextcloud/updater_server/blob/master/config/config.php#L108

latest **stable** is 16: https://github.com/nextcloud/updater_server/blob/master/config/config.php#L323

Thank you!

**Comment by jospoortvliet** [comment]
This is correct, as you can read in the announcement we roll out new releases slowly.

**Comment by Zelphy** [comment]
From https://nextcloud.com/blog/nextcloud-17-brings-remote-wipe-collaborative-text-editor-and-next-generation-secure-watermarking/

"note that we roll out new versions incrementally and usually wait a few weeks before we do so. This helps us catch any problems before it impacts too many users! If you wait for the updater to notify you, it can take some weeks. If you don’t want to wait, you can switch to the Beta channel, refresh the page, update to 17, and switch back!"

Thank you for pointing this out, sorry for the noise!

**Comment by jospoortvliet** [comment]
https://github.com/nextcloud/updater_server/pull/270
We've decided to delay until .1

**Comment by paulvt** [comment]
All my servers on production still report that 16.0.7 is the newest? I see in `config/config.php` that the release of 17.0.1 should have bumped it the rollout to 100% for that version and channel. Am I missing something here?
