### ISSUE TITLE
Time to release 16.0.6 to production, 17 to  30% stable?

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/updater_server#269]
Hi,

I propose we release 16.0.5 to production if that wasn't done already, and roll out 17 to 30% of stable users.

@rullzer @blizzz agreed?

**Comment by michag86** [comment]
15.0.12 is also missing on production channel.
@rullzer @blizzz @jospoortvliet Is there any reason why the latest bugfix versions are not released to production? This issue is open for four weeks!

**Comment by Aschenbecher** [comment]
You can update your title to "Time to release 16.0.6 to production" :D

**Comment by Peac** [comment]
16.0.6 is already released to production

**Comment by Aschenbecher** [comment]
> 16.0.6 is already released to production

Yes, now its online...thanks!

**Comment by blizzz** [comment]
indeed

**Comment by rcdailey** [comment]
One thing I don't understand is why the stable apache tag is still pointing to v16 and not v17. I believe Nextcloud 17 is stable right? What am I missing?
