### ISSUE TITLE
Release update for Nextcloud 10

### ISSUE THREAD

**Issue by zyberspace** [nextcloud/updater_server#6]
So i was wondering why my nextcloud instance (9.0.52) tells me that it is up-to-date while nextcloud 10 is actually the latest version.

First i thought it is because it's a new major release but it seems like the updater is fully capable of updating to a new major release.

But looking through the nextcloud repositories to find the _updater_ repo i found this one here and except this repository is outdated or you have an extra config for `https://updates.nextcloud.org/`, the `config/config.php` file is definitely missing the Nextcloud 10 release (i also went through the code a bit myself to see if i miss anything).

I would make a PR myself but i am not sure what else beside changing the config is needed to make the updater work (i guess testing if the automatic updater works with nextcloud 10 is one of these things?).

I am sry if this is not the right place for the issue but it would be nice if i could use the automatic updater instead of doing the manual process.

**Comment by LukasReschke** [comment]
Older releases than 9.0.54 don't use this updater. See https://nextcloud.com/blog/get-up-to-date-with-the-new-nextcloud-updater/ on information how to update.
