### ISSUE TITLE
migration issue

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/updater_server#66]
https://updates.nextcloud.org/owncloud-migration/?version=10x0x0x12xxxstablexx2017-04-26T11%3A44%3A04%2B00%3A00+ce40499f02717afa0af25bf2f67629a3159a29d3x5x6x30
gives empty.

That is, ownCloud 10.0.0.12 claims not to be updatable to Nc 12.

**Comment by LukasReschke** [comment]
Fixed.
