### ISSUE TITLE
Update server returns 500 ISE

### ISSUE THREAD

**Issue by jhstare** [nextcloud/updater_server#698]
Hi,

I'm currently running 21.0.1 and want to update. At first Nextcloud kept saying there was no update available, but after switching to the beta channel and back to stable again it now says "A new version is available: Nextcloud 21.0.7". When opening the webbased updater, it then reports:
```
Initializing
Current version is 21.0.1.
No update available.
```

```
$ sudo -u www-data php /var/www/nextcloud/occ upgrade
Nextcloud is already latest version
```

Looking at the updater log, I found the updateURL: https://updates.nextcloud.com/updater_server/?version=21x0x1x1xxxstablexx2021-04-08T13%3A32%3A52%2B00%3A00+bd555dbe8568b2509bd7d82fabbe38d76c86afbex7x4x3

The problem seems to be that the updater_server returns a 500 Internal Server Error:
```
$ curl "https://updates.nextcloud.com/updater_server/" -I
HTTP/1.0 500 Internal Server Error
Date: Fri, 21 Jan 2022 18:40:13 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Content-Security-Policy: default-src 'none'
Connection: close
Content-Type: text/html; charset=UTF-8
```

Could you guys please take a look at this?

Thanks!

**Comment by Donniewr** [comment]
This is why I'm getting the notification "Since 3 days update server could not be reached" ?

Using the latest stable version.

**Comment by skjnldsv** [comment]
On it

**Comment by skjnldsv** [comment]
Fixed, by bad everyone! Thanks you for reporting!
