### ISSUE TITLE
updater.phar times out.

### ISSUE THREAD

**Issue by edgarm1964** [nextcloud/updater_server#735]
LS,

whenever I want to run updater.phar, I get a timeout:

------------8<-----------------
sudo -u apache php /data/nextcloud/nextcloud/updater/updater.phar -vvv
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.9.

  [Exception]
  Could not do request to updater server: Operation timed out after 300182 milliseconds with 0 out of 0 bytes receive
  d

Exception trace:
 () at phar:///data/nextcloud/nextcloud/updater/updater.phar/lib/Updater.php:472
 NC\Updater\Updater->getUpdateServerResponse() at phar:///data/nextcloud/nextcloud/updater/updater.phar/lib/Updater.php:119
 NC\Updater\Updater->checkForUpdate() at phar:///data/nextcloud/nextcloud/updater/updater.phar/lib/UpdateCommand.php:147
 NC\Updater\UpdateCommand->execute() at phar:///data/nextcloud/nextcloud/updater/updater.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///data/nextcloud/nextcloud/updater/updater.phar/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at phar:///data/nextcloud/nextcloud/updater/updater.phar/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at phar:///data/nextcloud/nextcloud/updater/updater.phar/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at phar:///data/nextcloud/nextcloud/updater/updater.phar/updater.php:10
 require() at /data/nextcloud/nextcloud/updater/updater.phar:10

update [--no-backup]
------------8<-----------------

And the option 'verbose' doesn't seem to do anything. And the error is much too sparse and says nothing.

**Comment by skjnldsv** [comment]
Maybe some load on our side, should be good now

**Comment by edgarm1964** [comment]
Was an issue on my side: After my ISP changed my IPv6 address, the nextcloud server couldn't download anymore. The network configuration had some errors. After fixing them things work again. Sorry, for the inconvenience.
