### ISSUE TITLE
Nextcloud 12 deployment

### ISSUE THREAD

**Issue by kao98** [nextcloud/updater_server#82]
Hi,

Why don't you deploy Nextcloud 12 to Nextcloud 11 on the stable channel?

**Comment by MorrisJobke** [comment]
> Why don't you deploy Nextcloud 12 to Nextcloud 11 on the stable channel?

What do you mean by that?

**Comment by skyYaga** [comment]
I guess he wants to know when NC 11 users on the stable can upgrade to NC 12 via the updater.
Currently 100% of the NC 11 users will just be updated to 11.0.5.

**Comment by kao98** [comment]
Yes, that's it.

I've a NC 11 instance that keeps telling me it is up to date. Only the beta channel is configured with 
`
		'11' => [
			'100' => [
				'latest' => '12.0.3',
`

Stable and production are not
`
		'11' => [
			'100' => [
				'latest' => '11.0.5',
`

Why? NC12 isn't stable enough? Is NC11 a LTS release or something?

**Comment by MorrisJobke** [comment]
> Why? NC12 isn't stable enough? Is NC11 a LTS release or something?

No - we just want to be sure, that all the bad things don't happen anymore. So we waited for some time to announce it. But I guess we can now raise the amount of users that will be migrated from 11 to 12. cc @jospoortvliet @LukasReschke

**Comment by jospoortvliet** [comment]
Yeah, this has already been partially done, we should increase the number I guess. The web installer I also updated and asked to be deployed to our download server...

If you look at the code, the stable channelis still set to deliver 12.0.3 to users of Nextcloud 11:
https://github.com/nextcloud/updater_server/blob/master/config/config.php#L210

Let me make that 50% 12 and see if @LukasReschke accepts the PR 😸
