### ISSUE TITLE
extra files found - unable to update Nextcloud server

### ISSUE THREAD

**Issue by 4444cccc** [nextcloud/updater_server#824]
Hello,

I need to update nexcloud server to 25.0.3, but after starting the server update, it stops and says extra files found "datum". In "datum" folder are my files and system information. If I move it and update the config. php, nextcloud does not load at all. How to make the web update? Thanks!

**Comment by skjnldsv** [comment]
Hey!
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
If you search for existing thread, i'm sure you will be able to find plenty of similar issues previous users experienced with their setups :)

https://duckduckgo.com/?q=extra+files+found+unable+to+update+Nextcloud+server+site%3Ahelp.nextcloud.com&t=brave&ia=web
