### ISSUE TITLE
In "Beta" Channel the update "13.0.0 RC 1" is show for 12.0.4.

### ISSUE THREAD

**Issue by Tanarri** [nextcloud/updater_server#94]
I have Nextcloud 12.0.4 installed and I am in "beta "Channel

The updater show me the "13.0.0 RC 1" update, but it should be "12.0.5 RC 1"

The lines 285 ff in "config.php" are wrong:
```
		'12' => [
			'100' => [
				'latest' => '13.0.0 RC 1',
```

Greetings
TanarRi

**Comment by MorrisJobke** [comment]
I don’t think that they are wrong. We want to ship the 13 RC1 to 12 users

**Comment by MorrisJobke** [comment]
Works as it should -> closing
